import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import CategoryCard from '../components/categoryCard/categoryCard'
import ProductCard from '../components/productCard/productCard'

export async function getStaticProps(){
  const response = await fetch('https://assessment-edvora.herokuapp.com/')  
  const data = await response.json();

  let categories = {};
  data.forEach(element => {
    if(!categories[element.brand_name]){
      categories[element.brand_name] = [];
    }
    categories[element.brand_name].push(element)
  });
 

  return {
    props: {
      categories
    },
  };
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sectionWrapper}>
        <div className={styles.flexboxClass}>
          {/* <CategoryCard /> */}
          {/* <ProductCard /> */}
        </div>
      </div>

     
    </div>
  )
}
